### ISSUE TITLE
[SAKHI] Vaccination checklist

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/SAKHI#35]
Reference for vaccination checklist:
https://docs.google.com/spreadsheets/d/1cnKVDu6VIGpYzVkNh8PF-6wDoM-dXSmv/edit#gid=140620644

Make sure vaccination list is displaying all the mentioned vaccines for each age criteria of the child mentioned below.

- [x] Birth dose
- [x] 1.5 month dose
- [x] 2.5 month dose
- [x] 3.5 month dose
- [x] 9 month dose
- [x] 6 month dose
- [x] 5 years dose
- [x] 10 years dose
- [x] 16 years dose

**Comment by AchalaBelokar** [comment]
- [ ] Birth dose is missing  Hepatitis B , Vit K this dose needs add.
- [ ] suppose  child miss the vacation  what can we do.
- [ ] Tana Bana 2.5 months OPV 1, Penta 1 , Rota 1 , FIPV 1 ,PCV 1, missing the vaccinations. same for the other months



- [ ] 1.5  months child OPV 1 ,Penta 1 ,Rota 1, FIPV 1, PCV 1 these vaccinations  are missing

- [ ]  tana bana 2.5 months I changed  the date  in march so child is 24 week so that vaccination should  be shown  for 24 week child

**Comment by utkarshavni** [comment]
- [ ] Penta 3 is missing for Child aged 3.5 months or more. (Check "Anuj Anuj" or "Amar Akbar" in 21121 household).
- [ ] Doses after Vitamin A2 are not displayed for child aged more than 9 months. (Check "Amar Akbar")
- [ ] For "Anuj Anuj" child in 21121 Household, Penta 2 only displayed in Overdue while it should actually display Penta 3 since Penta 2 is already done.

**Comment by utkarshavni** [comment]
Attaching issues in this doc:
https://docs.google.com/document/d/1nntWnpjrdYib_Q5pE4HCYqwae1eMbT04cTJ5GHodP2w/edit

**Comment by nupoorkhandelwal** [comment]
Fixing for -
1. Pentavalent 2 - **done**
2. Measles 2 - **done**
3. JE 2 -**done**
4. DPT Booster 2 - **done**
5. OPV 3 - **done**
6. OPV Booster - **done**
